default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dzanikas # role previously added
  password: <%= ENV['DATABASE_PASSWORD'] %> # variable previously added

development:
  <<: *default
  database: flight_booker_development

test:
  <<: *default
  database: flight_booker_test

production:
  <<: *default
  database: flight_booker_production
  url: <%= ENV["DATABASE_URL"] %> # Used in deployment (Heroku, Render, etc.)